name: bump-nuget-version
run-name: Ensy Net Core - Bump NuGet Version on Release

on:
  release:
    types: [released]

permissions:
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from name
        id: nuget_version
        run: |
          title="${{ github.event.release.name }}"
          regex=".*v([0-9]+\.[0-9]+\.[0-9]+)(?![\-0-9]).*"

          [[ $title =~ $regex ]] || echo "No version could be found in release title."

          version=${BASH_REMATCH[1]}
          if [[ -z $version ]]; then 
            exit 1
          fi

          echo "Found version: $version"
          echo "nuget_version=$version" >> "$GITHUB_ENV"

      - name: Modify version file
        working-directory: ./src
        run: sed -i -E "s/(<Version>).*(<\/Version>)/\1${{ env.nuget_version }}\2/" Directory.Packages.props
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Bump nuget to v${{ env.nuget_version }}
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto/bump-nuget-v${{ env.nuget_version }}
          delete-branch: true
          title: '[AutoPR] Bump nuget version to v${{ env.nuget_version }}'
          labels: |
            nuget bump
            automated pr
          assignees: EnsyFane
          reviewers: EnsyFane
          draft: false
